// Generated by gencpp from file deepexpress_gazebo/float64stamped.msg
// DO NOT EDIT!


#ifndef DEEPEXPRESS_GAZEBO_MESSAGE_FLOAT64STAMPED_H
#define DEEPEXPRESS_GAZEBO_MESSAGE_FLOAT64STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>

namespace deepexpress_gazebo
{
template <class ContainerAllocator>
struct float64stamped_
{
  typedef float64stamped_<ContainerAllocator> Type;

  float64stamped_()
    : header()
    , data()  {
    }
  float64stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::Float64_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float64_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> const> ConstPtr;

}; // struct float64stamped_

typedef ::deepexpress_gazebo::float64stamped_<std::allocator<void> > float64stamped;

typedef boost::shared_ptr< ::deepexpress_gazebo::float64stamped > float64stampedPtr;
typedef boost::shared_ptr< ::deepexpress_gazebo::float64stamped const> float64stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepexpress_gazebo::float64stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepexpress_gazebo::float64stamped_<ContainerAllocator1> & lhs, const ::deepexpress_gazebo::float64stamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepexpress_gazebo::float64stamped_<ContainerAllocator1> & lhs, const ::deepexpress_gazebo::float64stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepexpress_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "830039f8f5aa832134c491ccbf30ca05";
  }

  static const char* value(const ::deepexpress_gazebo::float64stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x830039f8f5aa8321ULL;
  static const uint64_t static_value2 = 0x34c491ccbf30ca05ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepexpress_gazebo/float64stamped";
  }

  static const char* value(const ::deepexpress_gazebo::float64stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float64[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::deepexpress_gazebo::float64stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct float64stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepexpress_gazebo::float64stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepexpress_gazebo::float64stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPEXPRESS_GAZEBO_MESSAGE_FLOAT64STAMPED_H
